/*
 Navicat Premium Data Transfer

 Source Server         : mysql
 Source Server Type    : MySQL
 Source Server Version : 80027
 Source Host           : localhost:3306
 Source Schema         : games

 Target Server Type    : MySQL
 Target Server Version : 80027
 File Encoding         : 65001

*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for games_detail
-- ----------------------------
DROP TABLE IF EXISTS `games_detail`;
CREATE TABLE `games_detail`  (
  `game_id` int NOT NULL AUTO_INCREMENT COMMENT '游戏编号 ',
  `game_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '游戏名称',
  `game_poster` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '游戏封面',
  `game_inf1` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '游戏介绍1',
  `game_inf2` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '游戏介绍2',
  `game_video` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '游戏视频',
  `game_img1` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '游戏图片1',
  `game_img2` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '游戏图片2',
  `company` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '游戏公司',
  `read_count` int NOT NULL DEFAULT 0 COMMENT '阅读次数',
  `buy_count` int NOT NULL DEFAULT 0 COMMENT '购买次数',
  `writer` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0' COMMENT '作者',
  `class` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `uid` int NULL DEFAULT NULL,
  PRIMARY KEY (`game_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 34 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of games_detail
-- ----------------------------
INSERT INTO `games_detail` VALUES (2, 'Samurai Sword VR', '20220409061801565header.jpg', ' 江户时代，日本陷入一片混乱。 江户时代，日本陷入一片混乱。 江户时代，日本陷入一片混乱。唤醒你体内的武士之魂，拿起手里剑与武士刀，于各地出生入死，斩杀一切障碍与敌人！在虚拟现实中体验武士的世界。 欢迎来到古代日本。 ', '于这款游戏\r\nHTC Vive为你带来的虚拟现实动作游戏体验\r\n特色\r\n\r\n    斩断阻挡在你面前的一切（什么？飞过来一条鱼！？），获取高分，与他人一竞高下。\r\n\r\n    古色古香的日式音乐，令人身临其境。 \r\n\r\n    再现日本历史中的真实场景。\r\n\r\n    只能使用苦无的挑战关卡，到了考验你的忍技的时候了。\r\n\r\n    在天守阁中杀出一条血路，进行场面宏大的头目战。\r\n\r\n    可选择使用火焰、雷霆或是传统武士刀。\r\n\r\n    泛舟村野城畔，穿梭樱花树下，决战竹林之间，以及更多特色场景！\r\n\r\n\r\n坐姿或站立皆可游戏。但你想想，真正的武士会坐着战斗吗？\r\n\r\n本游戏当前仅支持HTC Vive。\r\n系统需求\r\n\r\n    最低配置:\r\n        操作系统: Windows 7 SP1, Windows 8.1 or Windows 10\r\n        处理器: Intel® i5-4590, AMD FX 8350 equivalent or better\r\n        内存: 4 GB RAM\r\n        显卡: NVIDIA GeForce® GTX 970, AMD Radeon™ R9 290 equivalent or better, Video Output: HDMI 1.4, DisplayPort 1.2 or newer\r\n        存储空间: 需要 2866 MB 可用空间\r\n        附注事项: 1x USB 2.0 or better port also required\r\n\r\n© 2014 SAT-BOX. All rights reserved', '20220409061801758video.webm', '20220409061801449img1.jpg', '20220409061801892img2.jpg', 'SAT-BOX', 2, 0, 'SAT-BOX', 'RPG', 15);
INSERT INTO `games_detail` VALUES (3, 'Demeo', '20220409062136381header.jpg', ' Adventurers, its time to unite! Adventurers, its time to unite! Adventurers, its time to unite! Gather your friends and battle the dark forces that have overtaken the world of Resolution Games award-winning RPG dungeon crawler, Demeo. ', 'Adventurers, its time to unite! A dark force has taken over the underworld in the RPG dungeon crawler, Demeo, and it’s a world you’re not likely to survive alone.\r\n\r\nAvailable now on SteamVR, this cross-platform cooperative adventure for up to four players will soon be available for traditional PC gaming play outside of VR, complete with cross-play and cross-platform support between VR and PC players. Wishlist this page for more details as they emerge from the dungeon.\r\nTake the mantle of the hunter, sorcerer, assassin, guardian, or bard, all with their own unique abilities and skills, and use them wisely if you are ever to stop the darkness that is Rackarn and Alfaragh.\r\nThe 5th Earth is a place of contrast, consisting of eight provinces stretching across mountains, forests, caves and oceans. It holds the beauty of a sunset over a meadow where sherp bunnies and brins feed their younglings, or perhaps a wedding taking place in the village of Torp. At the same time, there is also an ugly side. Maybe a reaver drags you down below in a murky river or a vílther attacking you as you explore the ruins of Castle Hollowmark.\r\n\r\nOne might state that The 5th Earth is an ancient coin with two sides - one light and one dark', '20220409062136851video.webm', '20220409062136283img1.jpg', '20220409062136844img2.jpg', 'Resolution Games', 3, 0, 'Resolution Games', 'RPG', 15);
INSERT INTO `games_detail` VALUES (4, '3DMark', '20220409062503966header.jpg', ' 3DMark 适用于希望从硬件中获得更多收益的游戏玩家，超频者和系统构建商。 3DMark拥有广泛的基准测试，可满足您测试 PC 性能所需的一切. 3DMark拥有广泛的基准测试，可满足您测试 PC 性能所需的一切. ', '关于这款软件\r\nPC 游戏是对性能的追求，是一个永无止境的升级，超频和调整系统周期，以获得更快的帧速率，更高的分辨率和更好的视觉效果。\r\n\r\n3DMark 是完成此任務的必要裝備。 20多年來，3DMark 一直是基準測試和比較 PC 性能的首選。\r\n\r\n总会有一款新游戏需要您的硬件拥有更高的性能， 而且总会有新的硬件为您的游戏提供更高的性能。 长此以往， 欢迎使用 3DMark，游戏玩家的基准测试。\r\n3DMark 包括游戏玩家基准测试和比较 PC 性能所需的一切。 它针对从轻便笔记本电脑到专用台式机的所有类型的 PC 设计了专用测试。 3DMark 将为您的硬件推荐最佳基准测试项目。\r\n\r\n3DMark 通过实时渲染极其苛刻的类似游戏的场景来测试系统的 GPU 和 CPU 性能。 基准测试运行得越快，您的得分就越高。 现在您的任务开始了。 您能做什么以获得更好的成绩？\r\n\r\n首先将 3DMark 得分与其他具有相同硬件的系统的结果进行比较。 低于平均分数可能表示散热，配置或组件故障。 高于平均分的分数表明您的硬件可能超频。如果您想知道您的 3DMark 分数与真实游戏性能的关系，那么 3DMark 将向您展示一系列热门游戏的期待帧速率。\r\n\r\n现在您可了解您的系统还有多少性能潜力。更新您的驱动程序，更新 Windows， 尝试不同的系统设置。 每次更改后运行 3DMark 以追踪性能的提升。 找出系统中的瓶颈并比较 3DMark 分数，以帮助选择下一个升级。 在 Steam 上的 3DMark 社区中心中寻求建议，分享技巧并展示您的系统。\r\n超频是一门需要技巧和精度的艺术。目标是挤出您的 GPU 和 CPU 的每一滴性能。其回报是免费的性能升级，以及推动硬件超越其常规性能的满足感。\r\n\r\n3DMark 是超频者的必备工具。 在超频之前和之后运行 3DMark 以测量性能增益。 使用自定义基准测试设置来探索 PC 的性能极限。 通过更改分辨率和其他设置，使 3DMark 测试或多或少地变得苛刻。\r\n\r\n运行 3DMark 压力测试以检查超频的稳定性和散热效果。 3DMark 压力测试循环运行，使系统在重负载下的运行时间比标准基准测试更长。\r\n\r\n挑战您的朋友以设置最高 3DMark 得分或争夺 3DMark Steam 排行榜中的头把交椅', '20220409062503402video.webm', '20220409062503562img1.jpg', '20220409062503148img2.jpg', ' UL	', 2, 0, ' UL	', 'RPG', 15);
INSERT INTO `games_detail` VALUES (5, 'Tentacular', '20220409063630800header.jpg', ' VR游戏《触手巧匠》讲述了一个大块头、热心肠的触手怪，努力寻找容身之处的故事。  VR游戏《触手巧匠》讲述了一个大块头、热心肠的触手怪，努力寻找容身之处的故事。   热心肠的触手怪，努力寻找容身之处的故事。   ', '有没有觉得自己像只章鱼、格格不入？在《触手巧匠》里，你就会化身这么一个大块头、热心肠、住在海里的触手怪，努力在这世上寻找你的容身之处。\r\n\r\n在热闹非凡的异域小岛卡尔玛上，你和人类一同长大，成为了这世界上力气最大的零杂工，却也阴差阳错地揭开了自己的出身之谜。挥舞起你的巨大触手，通过一系列活动项目和建设谜题，帮助你的人类朋友研究一种异常强大的神秘能量源，同时探寻自己的真正身世，顺便为自己的游乐园——创意沙盒模式，解锁各种要素！\r\n\r\n吸盘各就位！\r\n玩法看点\r\n\r\n    灵活触手！ 借助完全基于物理的触手和章鱼般结实牢固的吸盘，让世间万物悉数在握。\r\n    任务棘手！ 用上非线性思维和庞大触手，完成超过50道动脑谜题和动手活动，建造巨大的各色建筑。\r\n    建筑能手！ 在不断扩展的建设沙盒里，挥洒天马行空的创造力。\r\n\r\n系统需求\r\n\r\n    最低配置:\r\n        需要 64 位处理器和操作系统\r\n        操作系统: Windows 10\r\n        处理器: AMD FX-8370 / Intel Core i3-6100\r\n        内存: 8 GB RAM\r\n        显卡: NVIDIA GeForce GTX 970 / Radeon RX 480\r\n        网络: 宽带互联网连接\r\n        存储空间: 需要 2 GB 可用空间\r\n\r\n    推荐配置:\r\n        需要 64 位处理器和操作系统\r\n        操作系统: Windows 10\r\n        处理器: Intel Core i7-6950X / AMD Ryzen 7 2700X\r\n        内存: 12 MB RAM\r\n        显卡: GeForce GTX 1080 / Radeon RX Vega 64\r\n        网络: 宽带互联网连接\r\n        存储空间: 需要 2 GB 可用空间\r\n\r\n', '20220409063630791video.webm', '20220409063630183img1.jpg', '20220409063630285img2.jpg', ' Firepunchd Games UG', 3, 0, 'Devolver Digital', 'RPG', 15);
INSERT INTO `games_detail` VALUES (6, 'Space Slurpies', '20220409064721651header.jpg', ' 蛇、蛇行、吞吃！蛇、蛇行、吞吃！蛇、蛇行、吞吃！在这个多人街机游戏中，控制荧光蛇的长度和尺寸。收集尽可能多的食物，并在每个回合中存活下来，避免在快节奏的战斗中撞到自己和其他玩家。 ', '你能在啧啧蛇的多彩星系存活多久？在这个多人街机游戏中，控制荧光蛇的长度和尺寸。收集尽可能多的食物，并在每个回合中存活下来，避免在快节奏的战斗中撞到自己和其他玩家。收集食物的艺术令人既满足又放松。但是，别忘了提防其他玩家，因为他们可能会试图阻截你并设置陷阱！\r\n游戏玩法：\r\n● 每位玩家在6D空间中控制一条跟随其手部的蛇● 每当蛇吞吃食物时，就会增加长度\r\n● 随着它的成长，它也会进化并覆盖盔甲\r\n● 在不撞到自己或其他玩家的情况下存活最长的时间\r\n● 强大的玩家可以互相阻截、坑害对手以赢得游戏\r\n● 要想成为最长的啧啧蛇，请避开爵士小行星和其他障碍！\r\n亮点：\r\n● 享受超过20张独特而生动的地图● 跨平台多人游戏，包括配对以及与好友玩\r\n● 自定义你的蛇，使它独一无二 ', '20220409064721419video.webm', '20220409064721721img1.jpg', '20220409064721642img2.jpg', 'Starcade Arcade LLC', 2, 0, 'Starcade Arcade LLC', 'FPS', 35);
INSERT INTO `games_detail` VALUES (9, 'OVR Toolkit', '20220409070159150header.jpg', ' OVR Toolkit is a utility application designed to make viewing the desktop in VR simple and fast, it allows for viewing the desktop within VR, placing desktop windows around the world. and quickly switching between windows. ', 'Overview\r\nOVR Toolkit is a SteamVR Overlay utility designed to make viewing the desktop within VR easy and intuitive. OVR Toolkit allows you to display specific desktop windows, quickly select between them, use intuitive controls to navigate those windows, and use a virtual keyboard to type.\r\n\r\nEver wanted to reply to Discord messages without taking off your headset or looking through a nose piece? Ever wanted to pause that song you are listening to without fumbling around on your keyboard? Now you can with ease!\r\n\r\nOVR Toolkit is compatible with all SteamVR compatible headsets. The utility is being built with the Vive/Vive Pro, Valve Index, and Oculus Rift/Rift S in mind though WMR headsets are compatible too. (Compatible controllers require a trigger and grip)\r\nFeatures\r\n\r\n    Overlays over almost all SteamVR applications: OVR Toolkit will display on top of all your favorite titles! (VRChat, Beat Saber, mostly all SteamVR titles, etc.)\r\n    Desktop window viewing: Allows you to select a desktop window and display it above your hand, or pin it in the world around you.\r\n    Multiple desktop windows: Create multiple different windows and place them in the world around you.', '20220409070159309video.webm', '20220409070159813img1.jpg', '20220409070159668img2.jpg', 'Curtis English', 9, 0, 'Curtis English', 'FPS', 35);
INSERT INTO `games_detail` VALUES (11, 'Redout: Enhanced Edition', '20220409070637809header.jpg', ' 《红视》是对经典另类竞速作品《F-Zero》、《WipeOut》、《Rollcage》和《POD》的致敬之作。它拥有风格硬朗、速度与难度并存的丰满驾驶体验，让人沉浸在街机式竞速游戏的核心酷炫感之中。', '次世代反重力竞速来了！\r\n《红视》是对经典另类竞速作品《F-Zero》、《WipeOut》、《Rollcage》和《POD》的致敬之作。它拥有风格硬朗、速度与难度并存的丰满驾驶体验，让人沉浸在街机式竞速游戏的核心酷炫感之中。漂浮系统和驾驶模型都是根据物理规则真实打造：每一个转弯，每一次倾斜，硬刹车，加速，赛道的每一个弯道和扭曲都会对飞船施加其独特的力量。锐利的低多边形风格，融合拥有最先进阴影的网格和地形设计，以及由虚幻引擎所带来的光影效果，创造出美丽且能被瞬间识别的美学场景。吹着徐徐微风的海岸线，诡异而冰冷的景观，广阔的沙漠平原：半废弃状态下的地球上忧郁的反乌托邦式氛围将为速度最快、节奏最紧张、风景最美丽的未来风格竞速充当最好的背景。\r\n特色\r\n\r\n    在线多人游戏 - 与来自世界各地的12名玩家一起来一场真正的竞速挑战\r\n    可选VR支持 - Oculus Rift、HTC Vive或OSVR。拥有全新的闪亮驾驶舱视角！\r\n    生涯模式 - 超过100个赛事可以参与竞赛、体验，升级等级并改造你的飞船\r\n    多样化的世界 - 分布在灾后地球时代上5大位置的25张赛道地图，以及首领赛道\r\n    永不无聊 - 11种赛事类型，从经典竞速到创新的竞技场比赛和基于得分的耐力赛\r\n    打造你自己的故事 - 6支竞速队伍，各自需要不同的驾驶风格，4种越来越快的竞速类型\r\n    道具 - 10余种以竞速为核心的可升级道具：额外加速、护盾、自我维修机器人、先进吸引系统、气流强化器等\r\n    动听的音乐 - 完全支持5.1声道的动态音轨，速度越快，节奏越美妙！\r\n\r\n速度\r\n《红视》是有史以来速度最快的竞速游戏。如果你能驾驭得了的话。这个游戏的快并非体现在你在屏幕上看到的速度数字上，而是由震动、景观、飞驰而过的建筑、高速碰撞、视觉效果、音效和沉浸感结合在一起来体现：这一切的一切都是为了让你感觉自己的速度足够快。\r\n在线多人游戏\r\n挑战来自世界各地的最多12名玩家，看看谁才是《红视》历史上最优秀的飞行员！你觉得你有能力赢得这个称号吗？那就证明给我看。真正的荣耀就像是天空中燃烧着的火花。\r\n动态音轨\r\n让你的耳朵做好准备，来听听你从未听到过的最刺激的动态音轨吧。《红视》将增强你的游戏体验，超越视觉效果，让你沉浸在与你的游戏风格和赛道表现相呼应的音效和音乐组合之中。', '20220409070637171video.webm', '20220409070637902img1.jpg', '20220409070637426img2.jpg', '34BigThings srl', 3, 0, '34BigThings srl', 'FPS', 35);
INSERT INTO `games_detail` VALUES (12, 'SUPERHOT VR', '20220409071328322header.jpg', ' 亦真亦幻，难以分辨。从肉体到灵魂，都要相信自己。迎接 SUPERHOT VR 那久违的、华丽而又残忍的世界吧。敌人，如潮水，四面八方涌入房间子弹，几十枚，尖声呼啸穿过空气……等一下。这儿，好像有什么不同…… ', 'SUPERHOT 这款主视角射击游戏，打通了小心谋划策略与大胆搏杀进击之间的界限。在游戏中，人前进时，时间才前进。生命条不会恢复；弹药也不会随随便便投送。敌人，人数比你多，火力比你猛而你，只是孤身一人，要捡拾死去敌人的武器，去射击，去砍杀，还要穿行于低速移动的密集子弹之间，艰难前进。SUPERHOT VR ，专为虚拟现实、手势识别追踪手柄，重新构思，重新设计。游戏刚刚推出，即获诸多虚拟现实游戏年度奖项。三年多的锐意开拓，使得 SUPERHOT VR，将 SUPERHOT 震人心魄的激烈效果，直接投入到了你的脑海里、心灵中。现在又 - 直接投入到你 SteamVR 的虚拟现实世界中。2017 年 DICE 大奖虚拟现实游戏奖得主\r\n 2017 年 Unity Vision Summit 虚拟现实游戏奖得主\r\n 2017 年 Pixel 大奖最佳虚拟现实游戏奖得主\r\n 2017 年 Digital Dragons 最佳虚拟现实游戏奖得主\r\n 2017 年 GDCA 最佳虚拟现实游戏奖提名', '20220409071328299video.webm', '20220409071328706img1.jpg', '20220409071328984img2.jpg', ' SUPERHOT Team', 1, 0, ' SUPERHOT Team', 'FPS', 35);
INSERT INTO `games_detail` VALUES (13, 'DragonRideVR', '20220409071600245header.jpg', ' DragonRide VR是一款旨在让您沉浸在陆地、海洋陆地、海洋陆地、海洋陆地、海洋和天空的神奇世界中的互动式奇幻龙游戏。乘你自己的龙飞行或从各种预设的骑乘中选择！体验五种游戏模式，看看你在排行榜上排名如何吧。 ', '你曾经在一个奇幻的世界里乘龙而行吗?用DragonRide VR让这个梦想变成虚拟的现实!\r\n\r\n在一个神秘而有着互动的世界里，与这些美丽而真实的生物一起滑翔和飞行。把你的想象力放飞，因为你将发现在陆地、海洋和天空都有龙。将自己沉浸在4个奇幻世界中，如果你敢，甚至可以去深海中探寻。龙之旅VR适合所有年龄阶段的人!\r\n\r\n经验与特点：\r\n自由飞行——可以在陆地、海洋和天空完全地控制你定制的龙！以你的方式探索这些神奇世界。\r\n自由飞行游戏模式：\r\n\r\n    寻蛋：在时间耗尽之前找到丢失的龙蛋！\r\n    气球射击：尽可能多的使气球爆炸以获得分数！\r\n    圆环：使用你的技能在发光的圆环下降之前飞过它们\r\n\r\n！\r\n\r\nSteam排行榜：作为龙的主人，争夺榜一的位置吧！\r\n\r\n360°全景视角：在静止全景模式下，领略不同世界的美。\r\n\r\n乘龙：跳上龙背探索吧!包括行走、游泳和飞行在内的御龙模式可供选择!\r\n\r\n骑乘游戏模式——圈道＆时间挑战\r\n\r\n    在龙背上射击目标和气球！\r\n    技能射击和远距离射击都有奖励！\r\n    自动激活魔法咒语(当其持续时)来帮助你提高分数！在游戏中找到9种能量提升法术。\r\n\r\n\r\n我们持续发展的承诺：\r\nDragonRide VR将免费持续发布更新，包括新的世界、新的生物和新的游乐设施。 ', '20220409071600392video.webm', '20220409071600675img1.jpg', '20220409071600978img2.jpg', ' TypeEh Studios', 1, 0, ' TypeEh Studios', 'FPS', 35);
INSERT INTO `games_detail` VALUES (14, 'No Mans Sky', '20220409073910750header.jpg', ' 无人之地是一个科幻题材的游戏，需要玩家在一个按程序生成的无限宇宙中探索和生存。  无人之地是一个科幻题材的游戏，需要玩家在一个按程序生成的无限宇宙中探索和生存。  需要玩家在一个按程序生成的无限宇宙中探索和生存。 ', '开始一段史诗般的航行。\r\n在星系的中心，冥冥中有一个不可抗拒的吸引力，引领你去探索宇宙的真正奥义。但是，当面对攻击性的生物和凶猛的海盗，你将明白死亡亦有代价而生死存亡的关键往往取决于你如何升级飞船、武器和装备。\r\n找到命运真谛\r\n在‘无人之地’中，你的航行由你做主。你会成为一名战士，以侵略弱者为生，掠夺他们的财富，或掠夺海盗的战利品？掌握主动权，占据优势，升级飞船的速度和武器。\r\n还是会成为一名商人? 在这个被遗忘的世界里找到丰富的资源，利用它们获取高额利润。以此投资更多的货仓空间，你将获得巨额回报。\r\n\r\n亦或者成为一个探险家？超越已知领域，去发掘那些从来无人见过的地方和事物。升级你的引擎，带你飞得更远增强宇宙服性能，在有毒环境中得以生存，而大意者只能走向灭亡。\r\n分享你的旅程\r\n这个星系是一个有血有肉，生生不息的世界。贸易航队在星际间穿梭，各派争夺地盘，海盗乘火打劫，星际战警也一直虎视眈眈。其他玩家都生活在同一个星系中，你可以选择在已知太空的地图上与他们分享你的发现。这样你不仅能看到自己的内容，也许也能看到对方操作行动的结果……', '20220409073910905video.webm', '20220409073910437img1.jpg', '20220409073910942img2.jpg', 'Hello Games', 5, 0, 'Hello Games', 'SLG', 36);
INSERT INTO `games_detail` VALUES (15, 'Voxel Shot VR', '20220409074131610header.jpg', ' 这是一款VR动作类游戏，用你手中的各种武器，打败不断逼近的各种僵尸吧！ 那些看起来可爱，却很棘手的僵尸、直升机、大型BOSS，丧尸降临，你是否能够打败他们在世界末日存活下来？ 你是否能够打败他们在世界末日存活下来？ ', '这是一款VR动作类游戏，用你手中的各种武器，打败不断逼近的各种僵尸吧！\r\n那些看起来可爱，却很棘手的僵尸、直升机、大型BOSS，丧尸降临，你是否能够打败他们在世界末日存活下来？\r\n- 游戏特征 -\r\n\r\n    消灭可爱(?)的僵尸\r\n    手枪、突击抢、火箭炮、手榴弹，用你手中的武器存活下来！\r\n    City, Desert, Base, Airport –多种难易度的关卡任你选择\r\n    巨大僵尸、直升机、坦克，体验与各种敌人的战斗・・・\r\n    无尽模式，尽享击败僵尸的乐趣\r\n    全球排名，挑战世界高手，驰名全球！\r\n\r\n\r\n※初次体验时建议完成新手引导的体验！', '20220409074131408video.webm', '20220409074131121img1.jpg', '20220409074131627img2.jpg', 'SAT-BOX', 2, 0, 'SAT-BOX', 'SLG', 36);
INSERT INTO `games_detail` VALUES (16, 'Cooking Simulator VR', '20220409074336775header.jpg', ' 成为终极大厨！在样样俱全、装饰精美的逼真厨房里掌控一切！解锁并掌握超过80种食谱，使用数十种真实食材，烹饪出完美菜肴。全过程均采用真实物理效果！ 全过程均采用真实物理效果！ 全过程均采用真实物理效果！ ', '成为终极大厨！在样样俱全、装饰精美的逼真厨房里掌控一切！解锁并掌握超过80种食谱，使用数十种真实食材，烹饪出完美菜肴。全过程均采用真实物理效果！扒炉、煤气炉、烤箱、搅拌机……你的厨房可谓应有尽有。游戏中还有大量厨具，锅碗瓢盆一应俱全！食材种类超过120种！包括鱼肉蔬果、奶制品及各类液体。你还能用种类丰富的香草与香料来调味！', '20220409074336772video.webm', '20220409074336655img1.jpg', '20220409074336604img2.jpg', 'GameBoom VR', 1, 0, ' Big Cheese Studio, PlayWay S.A.', 'SLG', 36);
INSERT INTO `games_detail` VALUES (17, 'Half-Life: Alyx', '20220409074506237header.jpg', ' Valve 携 VR 大作《半衰期：爱莉克斯》重磅回归《半衰期》系列。 这个战斗故事发生在《半衰期》和《半衰期2》之间，是与邪恶的外星种族联合军之间看似毫无胜算的较量。 扮演爱莉克斯·凡斯，人类存活下去的唯一希望。 ', 'Valve 携 VR 大作《半衰期：爱莉克斯》重磅回归《半衰期》系列。 这个战斗故事发生在《半衰期》和《半衰期2》之间，是与邪恶的外星种族联合军之间看似毫无胜算的较量。\r\n\r\n扮演爱莉克斯·凡斯，人类存活下去的唯一希望。 在黑山基地事件之后，联合军把仅存的人类圈禁在城市中，对地球的铁腕控制只增不减。 人群之中有两位地球上最出色的科学家：您和您的父亲， 伊莱·凡斯博士。\r\n\r\n反抗势力尚未稳固，身为发起成员的你们，仍继续从事着秘密科学活动——展开至关重要的研究，为那些为数不多英勇抵抗联合军的人类打造宝贵的工具。\r\n\r\n每一天，你们对敌人的了解都更为深入；每一天，你们都在为找到他们的弱点而努力。\r\n\r\nVR 中的游戏玩法\r\n\r\nValve《半衰期》世界的回归之作，从一开始就是为虚拟现实量身打造的。 VR 就是为了让《半衰期》的核心游戏玩法得以呈现而构建。\r\n\r\n全身心沉浸在极具深度的环境交互、解决谜题、探索世界和几可乱真的战斗之中吧。\r\n\r\n侧身绕过断壁残垣、猫腰避开藤壶怪，开出原本不可能成功的一枪。 在架子上四处翻找治疗用注射器以及霰弹枪子弹。 操控工具黑入外星人接口。 朝窗外扔出一个瓶子来引开敌人注意。 把脸上的猎头蟹扯下来扔出窗外。\r\n\r\n社区创建的游戏环境\r\n\r\n游戏还包含一套能够打造新关卡的 Source 2 工具，让所有玩家都可以通过《半衰期：爱莉克斯》的 Steam 创意工坊打造全新环境，并贡献给整个社区共享同乐。 而 Valve 的关卡创作工具 Hammer 也已更新，包含了此游戏的所有虚拟现实游戏工具和组件。', '20220409074506316video.webm', '20220409074506381img1.jpg', '20220409074506844img2.jpg', ' Valve	', 32, 0, ' Valve	', 'SLG', 36);
INSERT INTO `games_detail` VALUES (18, 'Headshot VR', '20220409074640138header.jpg', ' 还记得在线射手的日子，记得在电脑俱乐部，情绪，肾上腺素，狂喜和愤怒不眠之夜。 多人射击游戏HeadShotVR将让您沉immerse在使用HTC Vive的虚拟现实的动态氛围中。让您沉immerse在使用HTC Vive的虚拟现实的动态氛围中。 ', '还记得在线射手的日子，记得在电脑俱乐部，情绪，肾上腺素，狂喜和愤怒不眠之夜。\r\n多人射击爆头VR将让您沉immerse在使用HTC Vive的虚拟现实的动态氛围中。\r\n产品特点:\r\n-多人游戏模式5x5\r\n-与玩家沟通（您可以与玩家交谈)\r\n-选择3（目前）的地图\r\n-7武器的选择\r\n-使用布局时控制武器\r\n-拍摄模式\r\n\r\n游戏玩家，这是一个beta测试，早期访问游戏！ 请理解的错误，并写信给我们，当你发现他们。\r\n许多问题已经解决，更改将在下一个版本中发布。 构建正在蒸汽测试。', '20220409074640444video.webm', '20220409074640555img1.jpg', '20220409074640765img2.jpg', ' VR Studio	', 2, 0, ' VR Studio	', 'SLG', 36);

SET FOREIGN_KEY_CHECKS = 1;
